import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PrivyProviders from "@/providers/privy";
import AppStateProvider from "@/providers/recoil";

const Inter = localFont({
  src: "./fonts/inter/Inter-Regular.otf",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className={`${Inter.className}`}>
        <AppStateProvider>
          <PrivyProviders>{children}</PrivyProviders>
        </AppStateProvider>
      </body>
    </html>
  );
}
